image: Ubuntu

environment:
  matrix:
    - PY: '3.8'
    - PY: '3.9'

build: off

install:
  - $HOME/venv$PY/bin/python -m pip install --upgrade pip wheel
  - $HOME/venv$PY/bin/python -m pip install -r requirements.txt

test_script:
  - $HOME/venv$PY/bin/python tinuous --help
