language: python
cache: pip
dist: focal
python:
  - '3.9'
  - '3.10'
  - '3.11'
  - '3.12'
  - '3.13'
env:
  - TOXENV=py
jobs:
  include:
    - python: '3.10'
      env: TOXENV=lint
    - python: '3.10'
      env: TOXENV=typing
install:
  - pip install tox
script:
  - tox
