name: Test fetching tinuous' logs

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        extra:
          - base
          - datalad
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install tinuous and coverage
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install coverage
          python -m pip install .

      - name: Install datalad and git-annex
        if: matrix.extra == 'datalad'
        run: |
          apt-get update && apt-get install -y git-annex
          python -m pip install datalad

      - name: Checkout con/tinuous-inception
        uses: actions/checkout@v2
        with:
          repository: con/tinuous-inception
          path: tinuous-inception

      - name: Configure datalad
        if: matrix.extra == 'datalad'
        run: |
          git config --global user.email "tinuous@nil"
          git config --global user.name "Tinuous Tester"

          sed -i -e 's:{year}/{month}/{day}:{year}//{month}//{day}:' tinuous.yaml
          echo "datalad:" >> tinuous.yaml
          echo "  enabled: true" >> tinuous.yaml
          echo "  cfg_proc: text2git" >> tinuous.yaml
        working-directory: tinuous-inception

      - name: Run tinuous on tinuous
        run: coverage run --source tinuous --branch -m tinuous fetch
        working-directory: tinuous-inception
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
          APPVEYOR_TOKEN: ${{ secrets.APPVEYOR_TOKEN }}

      - name: Coverage report
        run: |
          coverage report --precision 2 --show-missing
          coverage xml
        working-directory: tinuous-inception

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: tinuous-inception/coverage.xml
          fail_ci_if_error: false

# vim:set et sts=2:
