name: Test fetching tinuous' logs

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install tinuous and coverage
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install coverage
          python -m pip install .

      - name: Checkout con/tinuous-inception
        uses: actions/checkout@v2
        with:
          repository: con/tinuous-inception
          path: tinuous-inception

      - name: Run tinuous on tinuous
        run: coverage run --rcfile ../tox.ini -m tinuous fetch
        working-directory: tinuous-inception
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
          APPVEYOR_TOKEN: ${{ secrets.APPVEYOR_TOKEN }}

      - name: Report coverage
        run: coverage report --rcfile ../tox.ini
        working-directory: tinuous-inception

      - name: Generate coverage.xml
        run: coverage xml --rcfile ../tox.ini
        working-directory: tinuous-inception

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: tinuous-inception/coverage.xml
          fail_ci_if_error: false

# vim:set et sts=2:
